name: Sync from raw.githubusercontent.com

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sync files
        run: |
          git config --global user.email "zjxprograms2010@163.com"
          git config --global user.name "DGBlocksLite"
          curl -o file.txt https://raw.githubusercontent.com/DGBlocksLite/HWIDCheck/main/hwidcheck.txt
          git add hwidcheck.txt
          git commit -m "Sync hwidcheck.txt from raw.githubusercontent.com"
          git push
